site_name: Shotl MAAS (Beta)
site_dir: site
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: grey
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  icon:
    logo: images/logo
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
    - json
  features:
    - navigation.instant

extra_css:
  - assets/css/admonitions.css
  - assets/css/icons.css

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting started:
    - API Reference: getting-started/api-reference.md
    - Authentication:  getting-started/authentication.md
    - Errors: getting-started/errors.md
    - Versioning: getting-started/versioning.md
  - Guides:
    - Service availability: guides/service-availability.md
    - Users: guides/users.md
    - Areas: guides/areas.md
    - Stops: guides/stops.md
    - Vehicles: guides/vehicles.md
    - Rides:
      - Introduction: guides/rides/introduction.md
      - Status and transitions: guides/rides/status-and-transitions.md
      - Creating a ride: guides/rides/creating-ride.md
      - Getting info of a ride: guides/rides/info.md
      - Payments: guides/rides/payments.md
      - History: guides/rides/history.md
    - Legal docs: guides/legal-docs.md
    - Webhooks:
      - About: guides/webhooks/about.md
      - Configuration: guides/webhooks/creating.md
      - Security: guides/webhooks/security.md
      - Types: guides/webhooks/types.md
  - Changelog: changelog.md